import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TANAMI_TASK_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.SELECT,
    name: 'priority',
    label: 'Priority',
    description: 'Tanami RM task priority',
    icon: 'IconAlertTriangle',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'gray', label: 'Low', position: 0, value: 'LOW' },
      { color: 'blue', label: 'Medium', position: 1, value: 'MEDIUM' },
      { color: 'orange', label: 'High', position: 2, value: 'HIGH' },
      { color: 'red', label: 'Urgent', position: 3, value: 'URGENT' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'taskType',
    label: 'Task Type',
    description: 'RM action type for this task',
    icon: 'IconListCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'blue', label: 'Call', position: 0, value: 'CALL' },
      { color: 'green', label: 'WhatsApp', position: 1, value: 'WHATSAPP' },
      { color: 'purple', label: 'Email', position: 2, value: 'EMAIL' },
      {
        color: 'orange',
        label: 'Send Proposal',
        position: 3,
        value: 'SEND_PROPOSAL',
      },
      {
        color: 'yellow',
        label: 'KYC Follow-up',
        position: 4,
        value: 'KYC_FOLLOW_UP',
      },
      {
        color: 'turquoise',
        label: 'Investment Follow-up',
        position: 5,
        value: 'INVESTMENT_FOLLOW_UP',
      },
      { color: 'gray', label: 'Other', position: 6, value: 'OTHER' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'taskSource',
    label: 'Task Source',
    description: 'Whether the task was created manually or by Tanami systems',
    icon: 'IconSourceCode',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'gray', label: 'Manual', position: 0, value: 'MANUAL' },
      {
        color: 'blue',
        label: 'Trigger Engine',
        position: 1,
        value: 'TRIGGER_ENGINE',
      },
      { color: 'green', label: 'Platform', position: 2, value: 'PLATFORM' },
      { color: 'purple', label: 'Intercom', position: 3, value: 'INTERCOM' },
      {
        color: 'orange',
        label: 'CSV Upload',
        position: 4,
        value: 'CSV_UPLOAD',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'triggerType',
    label: 'Trigger Type',
    description: 'Tanami trigger that generated this task',
    icon: 'IconBellRinging',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'yellow',
        label: 'User Inactivity',
        position: 0,
        value: 'USER_INACTIVITY',
      },
      {
        color: 'orange',
        label: 'Re-engagement',
        position: 1,
        value: 'RE_ENGAGEMENT',
      },
      {
        color: 'purple',
        label: 'Client Dormancy',
        position: 2,
        value: 'CLIENT_DORMANCY',
      },
      {
        color: 'blue',
        label: 'Account Growth',
        position: 3,
        value: 'ACCOUNT_GROWTH',
      },
      {
        color: 'red',
        label: 'High-value Unassigned',
        position: 4,
        value: 'HIGH_VALUE_UNASSIGNED',
      },
      {
        color: 'gray',
        label: 'Manual Follow-up',
        position: 5,
        value: 'MANUAL',
      },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'triggerKey',
    label: 'Trigger Key',
    description: 'Machine-readable trigger identifier from Tanami',
    icon: 'IconKey',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'snoozedUntil',
    label: 'Snoozed Until',
    description: 'When a snoozed RM task should reappear',
    icon: 'IconClockPause',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'dismissedAt',
    label: 'Dismissed At',
    description: 'When a trigger-generated task was dismissed',
    icon: 'IconCircleOff',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'snoozeOrDismissReason',
    label: 'Snooze/Dismiss Reason',
    description: 'Reason logged when an RM snoozes or dismisses a trigger',
    icon: 'IconMessageCircle',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'completedAt',
    label: 'Completed At',
    description: 'When the RM completed this task',
    icon: 'IconCircleCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'externalTaskId',
    label: 'External Task ID',
    description: 'Task ID from Tanami or another upstream system',
    icon: 'IconExternalLink',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'idempotencyKey',
    label: 'Idempotency Key',
    description: 'Stable key used to avoid duplicate trigger-generated tasks',
    icon: 'IconFingerprint',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
];
