import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TANAMI_ASSIGNMENT_HISTORY_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] =
  [
    {
      type: FieldMetadataType.SELECT,
      name: 'assignmentType',
      label: 'Assignment Type',
      description: 'Whether the assignment was automatic or manual',
      icon: 'IconRoute',
      isActive: true,
      isNullable: true,
      isUnique: false,
      options: [
        { color: 'blue', label: 'Automatic', position: 0, value: 'AUTOMATIC' },
        { color: 'purple', label: 'Manual', position: 1, value: 'MANUAL' },
      ],
    },
    {
      type: FieldMetadataType.TEXT,
      name: 'reason',
      label: 'Reason',
      description: 'Assignment reason or rule explanation',
      icon: 'IconMessageCircle',
      isActive: true,
      isNullable: true,
      isUnique: false,
    },
    {
      type: FieldMetadataType.DATE_TIME,
      name: 'assignedAt',
      label: 'Assigned At',
      description: 'When this RM assignment started',
      icon: 'IconCalendarCheck',
      isActive: true,
      isNullable: true,
      isUnique: false,
    },
    {
      type: FieldMetadataType.DATE_TIME,
      name: 'endedAt',
      label: 'Ended At',
      description: 'When this RM assignment ended',
      icon: 'IconCalendarOff',
      isActive: true,
      isNullable: true,
      isUnique: false,
    },
    {
      type: FieldMetadataType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Whether this assignment row is active or historical',
      icon: 'IconCircleCheck',
      isActive: true,
      isNullable: true,
      isUnique: false,
      options: [
        { color: 'green', label: 'Active', position: 0, value: 'ACTIVE' },
        { color: 'gray', label: 'Ended', position: 1, value: 'ENDED' },
      ],
    },
  ];

export const TANAMI_INVESTMENT_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'externalInvestmentId',
    label: 'External Investment ID',
    description: 'Investment ID from Tanami',
    icon: 'IconId',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'status',
    label: 'Status',
    description: 'Latest investment status',
    icon: 'IconProgressCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'yellow', label: 'Pending', position: 0, value: 'PENDING' },
      { color: 'green', label: 'Active', position: 1, value: 'ACTIVE' },
      { color: 'orange', label: 'Redeemed', position: 2, value: 'REDEEMED' },
      { color: 'red', label: 'Cancelled', position: 3, value: 'CANCELLED' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'productName',
    label: 'Product Name',
    description: 'Investment product name',
    icon: 'IconPackage',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'amount',
    label: 'Amount',
    description: 'Committed or invested amount',
    icon: 'IconCash',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE,
    name: 'investedAt',
    label: 'Invested At',
    description: 'Date the investment became active',
    icon: 'IconCalendarDollar',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];

export const TANAMI_TRANSACTION_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'externalTransactionId',
    label: 'External Transaction ID',
    description: 'Transaction ID from Tanami',
    icon: 'IconId',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'transactionType',
    label: 'Transaction Type',
    description: 'Type of Tanami transaction',
    icon: 'IconArrowsTransferUpDown',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'green', label: 'Deposit', position: 0, value: 'DEPOSIT' },
      {
        color: 'orange',
        label: 'Withdrawal',
        position: 1,
        value: 'WITHDRAWAL',
      },
      { color: 'blue', label: 'Investment', position: 2, value: 'INVESTMENT' },
      {
        color: 'purple',
        label: 'Distribution',
        position: 3,
        value: 'DISTRIBUTION',
      },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'status',
    label: 'Status',
    description: 'Latest transaction status',
    icon: 'IconProgressCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'yellow', label: 'Pending', position: 0, value: 'PENDING' },
      { color: 'green', label: 'Completed', position: 1, value: 'COMPLETED' },
      { color: 'red', label: 'Failed', position: 2, value: 'FAILED' },
      { color: 'gray', label: 'Cancelled', position: 3, value: 'CANCELLED' },
    ],
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'amount',
    label: 'Amount',
    description: 'Transaction amount',
    icon: 'IconCash',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'occurredAt',
    label: 'Occurred At',
    description: 'When the transaction occurred',
    icon: 'IconClock',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];

export const TANAMI_KYC_CASE_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'externalKycCaseId',
    label: 'External KYC Case ID',
    description: 'KYC case ID from Tanami',
    icon: 'IconId',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'status',
    label: 'Status',
    description: 'Latest KYC case status',
    icon: 'IconShieldCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'gray',
        label: 'Not Started',
        position: 0,
        value: 'NOT_STARTED',
      },
      { color: 'yellow', label: 'In Review', position: 1, value: 'IN_REVIEW' },
      { color: 'green', label: 'Approved', position: 2, value: 'APPROVED' },
      { color: 'red', label: 'Rejected', position: 3, value: 'REJECTED' },
      { color: 'orange', label: 'Expired', position: 4, value: 'EXPIRED' },
    ],
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'submittedAt',
    label: 'Submitted At',
    description: 'When KYC was submitted',
    icon: 'IconCalendarUp',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'reviewedAt',
    label: 'Reviewed At',
    description: 'When KYC was reviewed',
    icon: 'IconCalendarCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'reviewNotes',
    label: 'Review Notes',
    description: 'Latest KYC review notes',
    icon: 'IconNotes',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];

export const TANAMI_TRIGGER_EVENT_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'triggerKey',
    label: 'Trigger Key',
    description: 'Machine-readable trigger identifier from Tanami',
    icon: 'IconKey',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'status',
    label: 'Status',
    description: 'Trigger handling status',
    icon: 'IconProgressCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'yellow', label: 'Open', position: 0, value: 'OPEN' },
      {
        color: 'blue',
        label: 'Task Created',
        position: 1,
        value: 'TASK_CREATED',
      },
      { color: 'green', label: 'Handled', position: 2, value: 'HANDLED' },
      { color: 'gray', label: 'Ignored', position: 3, value: 'IGNORED' },
    ],
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'firedAt',
    label: 'Fired At',
    description: 'When the trigger fired',
    icon: 'IconBellRinging',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'reason',
    label: 'Reason',
    description: 'Human-readable trigger reason',
    icon: 'IconMessageCircle',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];

export const TANAMI_PLATFORM_ACTIVITY_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] =
  [
    {
      type: FieldMetadataType.SELECT,
      name: 'activityType',
      label: 'Activity Type',
      description: 'Type of platform activity',
      icon: 'IconActivity',
      isActive: true,
      isNullable: true,
      isUnique: false,
      options: [
        { color: 'blue', label: 'Login', position: 0, value: 'LOGIN' },
        {
          color: 'green',
          label: 'Account Created',
          position: 1,
          value: 'ACCOUNT_CREATED',
        },
        {
          color: 'purple',
          label: 'KYC Updated',
          position: 2,
          value: 'KYC_UPDATED',
        },
        {
          color: 'orange',
          label: 'Investment Viewed',
          position: 3,
          value: 'INVESTMENT_VIEWED',
        },
        {
          color: 'yellow',
          label: 'Document Uploaded',
          position: 4,
          value: 'DOCUMENT_UPLOADED',
        },
        { color: 'gray', label: 'Other', position: 5, value: 'OTHER' },
      ],
    },
    {
      type: FieldMetadataType.DATE_TIME,
      name: 'occurredAt',
      label: 'Occurred At',
      description: 'When the activity occurred',
      icon: 'IconClock',
      isActive: true,
      isNullable: true,
      isUnique: false,
    },
    {
      type: FieldMetadataType.TEXT,
      name: 'source',
      label: 'Source',
      description: 'System that emitted the platform activity',
      icon: 'IconSourceCode',
      isActive: true,
      isNullable: true,
      isUnique: false,
    },
  ];

export const TANAMI_CALL_NOTE_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'calledAt',
    label: 'Call Date & Time',
    description: 'Date and time when the RM call happened',
    icon: 'IconCalendarTime',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'sentiment',
    label: 'Sentiment',
    description: 'RM assessment of the contact sentiment after the call',
    icon: 'IconMoodSmile',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'red', label: 'Hot', position: 0, value: 'HOT' },
      { color: 'orange', label: 'Warm', position: 1, value: 'WARM' },
      { color: 'gray', label: 'Neutral', position: 2, value: 'NEUTRAL' },
      { color: 'blue', label: 'Cold', position: 3, value: 'COLD' },
    ],
  },
  {
    type: FieldMetadataType.RATING,
    name: 'conversionLikelihood',
    label: 'Likelihood of Conversion',
    description: 'Likelihood of conversion for prospects and users',
    icon: 'IconStars',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { label: '1', position: 0, value: 'RATING_1' },
      { label: '2', position: 1, value: 'RATING_2' },
      { label: '3', position: 2, value: 'RATING_3' },
      { label: '4', position: 3, value: 'RATING_4' },
      { label: '5', position: 4, value: 'RATING_5' },
    ],
  },
  {
    type: FieldMetadataType.MULTI_SELECT,
    name: 'productsInterestedIn',
    label: 'Products Interested In',
    description: 'Tanami products the contact showed interest in',
    icon: 'IconPackages',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'purple', label: 'PE', position: 0, value: 'PE' },
      {
        color: 'blue',
        label: 'Private Credit',
        position: 1,
        value: 'PRIVATE_CREDIT',
      },
      {
        color: 'green',
        label: 'Infrastructure',
        position: 2,
        value: 'INFRASTRUCTURE',
      },
      {
        color: 'turquoise',
        label: 'Liquid+',
        position: 3,
        value: 'LIQUID_PLUS',
      },
      {
        color: 'orange',
        label: 'Real Estate',
        position: 4,
        value: 'REAL_ESTATE',
      },
      { color: 'gray', label: 'Other', position: 5, value: 'OTHER' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'nextActionType',
    label: 'Next Action Type',
    description: 'Next action the RM should take after this call',
    icon: 'IconArrowForwardUp',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'blue', label: 'Send Doc', position: 0, value: 'SEND_DOC' },
      {
        color: 'green',
        label: 'Schedule Follow-up',
        position: 1,
        value: 'SCHEDULE_FOLLOW_UP',
      },
      { color: 'orange', label: 'Escalate', position: 2, value: 'ESCALATE' },
      { color: 'gray', label: 'No Action', position: 3, value: 'NO_ACTION' },
    ],
  },
  {
    type: FieldMetadataType.DATE,
    name: 'nextFollowUpDate',
    label: 'Next Follow-up Date',
    description: 'Follow-up date surfaced on the RM dashboard',
    icon: 'IconCalendarPlus',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'notes',
    label: 'Free Text Notes',
    description: 'Unstructured RM call narrative',
    icon: 'IconNotes',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];
