import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const TANAMI_PERSON_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.TEXT,
    name: 'tanamiContactId',
    label: 'Tanami Contact ID',
    description: 'Canonical CRM Contact ID from Tanami',
    icon: 'IconId',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'tanamiUserId',
    label: 'Tanami User ID',
    description: 'Tanami platform user ID when the contact has registered',
    icon: 'IconUserCode',
    isActive: true,
    isNullable: true,
    isUnique: true,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'lifecycleStage',
    label: 'Lifecycle Stage',
    description: 'Tanami lifecycle stage for this contact',
    icon: 'IconUserUp',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'yellow', label: 'Prospect', position: 0, value: 'PROSPECT' },
      { color: 'blue', label: 'User', position: 1, value: 'USER' },
      { color: 'green', label: 'Client', position: 2, value: 'CLIENT' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'source',
    label: 'Source',
    description: 'Original source that created or captured the contact',
    icon: 'IconSourceCode',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'gray', label: 'Manual', position: 0, value: 'MANUAL' },
      {
        color: 'purple',
        label: 'CSV Upload',
        position: 1,
        value: 'CSV_UPLOAD',
      },
      { color: 'blue', label: 'Intercom', position: 2, value: 'INTERCOM' },
      { color: 'green', label: 'Platform', position: 3, value: 'PLATFORM' },
      { color: 'orange', label: 'Website', position: 4, value: 'WEBSITE' },
      { color: 'turquoise', label: 'Referral', position: 5, value: 'REFERRAL' },
      { color: 'red', label: 'Other', position: 6, value: 'OTHER' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'sourceExternalId',
    label: 'Source External ID',
    description: 'ID from the original external source system',
    icon: 'IconExternalLink',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'country',
    label: 'Country',
    description: 'Country used by Tanami assignment rules',
    icon: 'IconWorld',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'preferredLanguage',
    label: 'Preferred Language',
    description: 'Preferred language used by RM assignment rules',
    icon: 'IconLanguage',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      { color: 'blue', label: 'English', position: 0, value: 'ENGLISH' },
      { color: 'green', label: 'Arabic', position: 1, value: 'ARABIC' },
      { color: 'purple', label: 'French', position: 2, value: 'FRENCH' },
      { color: 'gray', label: 'Other', position: 3, value: 'OTHER' },
    ],
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'rmAssignedAt',
    label: 'RM Assigned At',
    description: 'When the current RM assignment became active',
    icon: 'IconCalendarCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'kycStatus',
    label: 'KYC Status',
    description: 'Latest KYC status synchronized from Tanami',
    icon: 'IconShieldCheck',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'gray',
        label: 'Not Started',
        position: 0,
        value: 'NOT_STARTED',
      },
      {
        color: 'yellow',
        label: 'In Progress',
        position: 1,
        value: 'IN_PROGRESS',
      },
      { color: 'green', label: 'Approved', position: 2, value: 'APPROVED' },
      { color: 'red', label: 'Rejected', position: 3, value: 'REJECTED' },
      { color: 'orange', label: 'Expired', position: 4, value: 'EXPIRED' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'investmentStatus',
    label: 'Investment Status',
    description: 'Latest investment status synchronized from Tanami',
    icon: 'IconChartBar',
    isActive: true,
    isNullable: true,
    isUnique: false,
    options: [
      {
        color: 'gray',
        label: 'No Investment',
        position: 0,
        value: 'NO_INVESTMENT',
      },
      { color: 'yellow', label: 'Pending', position: 1, value: 'PENDING' },
      { color: 'green', label: 'Invested', position: 2, value: 'INVESTED' },
      { color: 'orange', label: 'Redeemed', position: 3, value: 'REDEEMED' },
    ],
  },
  {
    type: FieldMetadataType.CURRENCY,
    name: 'aum',
    label: 'AuM',
    description: 'Latest assets under management synchronized from Tanami',
    icon: 'IconCash',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
  {
    type: FieldMetadataType.DATE_TIME,
    name: 'lastPlatformActivityAt',
    label: 'Last Platform Activity At',
    description: 'Most recent platform activity synchronized from Tanami',
    icon: 'IconActivity',
    isActive: true,
    isNullable: true,
    isUnique: false,
  },
];
